# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20160125_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet2user_details',
            new_name='wallet2store_details',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 10, 40, 4, 840321)),
        ),
    ]
