# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20160126_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='transaction_method_remarks',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_method_name',
        ),
    ]
