# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20160128_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='hmac_or_checksum',
            field=models.CharField(default='temp_HMAC', max_length=200),
        ),
    ]
