# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20160128_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transaction_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
