# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_auto_20160128_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='hmac_or_checksum',
        ),
    ]
